### ISSUE TITLE
POST doesn't do what is expected if "Content-Type application/json" not specified

### ISSUE THREAD

**Issue by earldean** [NTIA/scos-sensor#100]
Using Postman, when performing a Post to _https://greyhound3.sms.internal/api/v1/schedule_ with the body below, the return value is 200 and a list of all the schedules, but the posted schedule is not created.  

```
{
	"name": "postman-test",
	"action": "acquire700c",
	"priority": 10,
	"start": "",
	"stop": "",
	"interval": 180,
	"stop_is_relative": "false"
}
```

**Comment by earldean** [comment]
I did not have 'Content-Type application\json' in header, adding that fixed it.

**Comment by djanderson** [comment]
What did you have for content type?

**Comment by earldean** [comment]
I did not specify.

**Comment by aromanielloNTIA** [comment]
Closing this, as it is outdated. I have just tested adding a schedule entry using a POST, and it works both with and without specifying the Content-Type header.
