### ISSUE TITLE
Interval's Spinner

### ISSUE THREAD

**Issue by linhvu1** [NTIA/scos-sensor#106]
The interval has to be more than 0 but its spinner on schedule page lets the user choose negative infinity. It would be nice to set a limit for it.

**Comment by djanderson** [comment]
This is good feedback, but the entire frontend is autogenerated from the models and serializers that we have defined. The model defines interval as a positive integer with min value of 1:

```python
    interval = models.PositiveIntegerField(
        null=True,
        blank=True,
        validators=(MinValueValidator(1),),
        help_text="Seconds between tasks, or leave blank to run once"
    )
```

But that doesn't seem to propagate out to the frontend. I just tried manually marking the serializer as min_value = 1 as well, but that also didn't prop out to the frontend.

In this case, we're just going to have to rely on the feedback from the backend and common sense that a negative time interval isn't valid :)

Keep 'em coming!
