### ISSUE TITLE
Add puppet variable for sentry-io

### ISSUE THREAD

**Issue by djanderson** [NTIA/scos-sensor#109]
env var SENTRY_DSN should be set with our account's DSN.

**Comment by djanderson** [comment]
@bradeales please review https://github.com/NTIA/scos-sensor/commit/631b05a538de5a00eb590fcad1c547a0f80e4008

**Comment by bradeales** [comment]
Just one small correction needed.

**Comment by djanderson** [comment]
Fixed, thanks.
