### ISSUE TITLE
Drop ~250k samples from acquisition to allow B210 to complete IQ  balancing

### ISSUE THREAD

**Issue by djanderson** [NTIA/scos-sensor#120]
Inlining a comment from slack:

> Todd Schumann [14:48]
> So the B210 apparently has no way to run a calibration utility for IQ imbalance. The actual radio (the AD9361) has an auto IQ algorithm built into it where it compares the long-term phase offset between I and Q and corrects that. So the longer the data stream is active, the better the IQ correction will be. For a single sine wave input (probably the easiest thing to correct), running an extra 200k samples at the beginning dropped the IQ imbalance into the noise. I don't know how the scos sensors are set up, but keeping the radio taking data (even if you just throw it away) will greatly help with the balance

SCOS sensor currently arbitrarily drops the first 1000 samples from the input stream... Todd found that the AD3961's IQ balancer takes closer to 200k to quiet down, so we should adjust scos sensor's number accordingly:

https://github.com/NTIA/scos-sensor/blob/master/src/actions/usrp.py#L119

@ToddSchumann, please follow up here with any info you have about LO settling times as well, since we might need to wait even longer at the beginning of an acquisition, since a scos sensor acquisition can't assume it is already at the target frequency.

**Comment by ToddSchumann** [comment]
The number is still rather arbitrary. The setup was a single CW signal placed about half the bandwidth away from the center LO frequency. The IQ imbalance peak reduced approximately 10dB per decade of extra samples taken at the beginning:
20dBm over noise with 2k samples
10dBm over noise with 20k samples
Indistinguishable from noise with 200k samples
The test used a clock/sampling frequency of 48/12MHz with 2048 samples per FFT taken. and was pretty consistent at each LO frequency I tried (100MHz to several GHz).

I'm going to run some additional tests to get more quantitative data, especially with sweeping. It would be nice to know if the samples need to be dumped after tuning the LO every single time or if it only needs to be done when cold.
