### ISSUE TITLE
Action specification

### ISSUE THREAD

**Issue by MichaelCotton** [NTIA/scos-sensor#123]
Wrt README.M/Browsable API/scheduling an action short form/Action...

The example gives Action
acquire 700c - Apply m4s detector over 300 1024-point FFTs at 751.00 MHz

It would be helpful to see some reference to sigmf-ns-scos/measurement_type, i.e.,  `SingleFrequencyFFTDetection`

The bigger issue is algorithm specification. Where do we document algorithms running on scos-sensor: scos-sensor or sigmf-ns-scos?

**Comment by djanderson** [comment]
Fixed in release v0.1.
