### ISSUE TITLE
scos-sensor actions should properly document SigMF extensions.

### ISSUE THREAD

**Issue by jhazentia** [NTIA/scos-sensor#153]
https://github.com/gnuradio/SigMF/blob/master/sigmf-spec.md#the-extensions-field

https://github.com/gnuradio/SigMF/pull/105

**Comment by aromanielloNTIA** [comment]
This has been addressed as part of #244 

Note that the extensions array is still not dynamically populated based on which extensions have actually been used in a given metadata file, but the format is now correct/up-to-date with SigMF
